<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class PostRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'title' => 'required|string',
            'summary' => 'required|string',
            'content' => 'required|string',
            'images' => 'nullable',
            'images.*' => 'mimes:jpeg,jpg,png|max:60',
        ];
    }
    public function messages()
    {
//        return parent::messages(); // TODO: Change the autogenerated stub
        return [
            'required' => 'the attribute field is required',
            'alpha'=>'insert only alphabetic chars for title',
            'mimes' => 'most be type of :  jpeg,jpg,png',
            'max'=>'most be lower than 60 KB',
        ];
    }
}
