<?php

namespace App\Exceptions;

use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Throwable;

class Handler extends ExceptionHandler
{
    /**
     * A list of the exception types that are not reported.
     *
     * @var array
     */
    protected $dontReport = [
        //
    ];

    /**
     * A list of the inputs that are never flashed for validation exceptions.
     *
     * @var array
     */
    protected $dontFlash = [
        'current_password',
        'password',
        'password_confirmation',
    ];

    /**
     * Register the exception handling callbacks for the application.
     *
     * @return void
     */
    public function register()
    {
        $this->reportable(function (Throwable $e) {
            //
        });
    }

    public function render($request, Throwable $e)
    {

        /*error handler api
        if page not found || error int/0
        */
        if ($request->wantsJson()) {
            $e = $this->prepareException($e);
            dd($e->getMessage(),$e->getCode(),$e->getStatusCode());
            $code = method_exists($e, 'getStatusCode') ? $e->getStatusCode() : $e->getCode();
//            dd($code);
            return response(['message' => $e->getMessage()], empty($code) ? 500 : $code);
        }
        return parent::render($request, $e); // TODO: Change the autogenerated stub
    }
}
